### ISSUE TITLE
"Open file"-dialog does not seem to work on Mac

### ISSUE THREAD

**Issue by mueller-physics** [fairSIM/fairSIM#26]
Every time the "open file" dialog is requested, fairSIM and Fiji freezes on Mac. This has only been tested on one machine so far, so first check if it reproduces.

**Comment by iandobbie** [comment]
I see a slightly different issue on my machine. I have just built from the latest source and linked against java 1.8 on macos 10.13.3. 

2d reconstruction seems to work fine. So opening files, creating new windows etc works fine for that.  I am able to setup a machine definition including loading and converting OMX style OTFs. However starting a 3d reconstruction locks up imageJ.

**Comment by iandobbie** [comment]
The same happens if I try to edit a machine file , so it looks like its the machine panel selector dialog that is crashing things.

**Comment by mueller-physics** [comment]
Yes, on Lothar machine it specifically crashed each time a machine definition was to be loaded, i.e. it did not even get to the stage it would display the file chooser (which is way before any XML parser code or something similarly likely to crash).
I've merged your fix and will close this for now, hopefully remembering to look into this once I have an OS X system set up here.

**Comment by iandobbie** [comment]
Marcel Müller <notifications@github.com> writes:

> Yes, on Lothar machine it specifically crashed each time a machine
> definition was to be loaded, i.e. it did not even get to the stage it
> would display the file chooser (which is way before any XML parser
> code or something similarly likely to crash).  I've merged your fix
> and will close this for now, hopefully remembering to look into this
> once I have an OS X system set up here.

Yes exactly the symptoms I found. I was just trying to narrow down
where it was failing and that log line solved it on my machine. I will
send a built jar to Lothar and Maria (the diamond person) and see if it
works for them. I am also extremely confused about why it fixes the
problem as I can't see any reason it should.

Ian
