### ISSUE TITLE
Java package doesnt exist

### ISSUE THREAD

**Issue by bbhskran** [fairSIM/fairSIM#34]
org\fairsim\linalg\JTransformsForkConnector.java:22: error: package org.fairsim.extern.jtransforms does not exist
[ERROR] import org.fairsim.extern.jtransforms.*;

**Comment by mueller-physics** [comment]
When running fairSIM, you need JTransforms in the classpath as an external library. You can use either the fork provided [here](https://github.com/fairSIM/JTransforms) or the original version of the library provided [here](https://github.com/wendykierp/JTransforms).

When building fairSIM, you need BOTH libraries accessible, as the connector plugin sees them as external dependencies. You can do so by adding https://github.com/fairSIM/JTransforms/releases/download/v1.0.0/jtransforms_fairSIM_fork.jar to your external libraries.

**Comment by bbhskran** [comment]
Thank you for your immediate response . I was able to resolve the issue as per the suggestion provided

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
