### ISSUE TITLE
bad html entity while building the code

### ISSUE THREAD

**Issue by bbhskran** [fairSIM/fairSIM#35]
org\fairsim\extern\jtransforms\FloatFFT_1D.java:1159: error: bad HTML entity
[ERROR]             if (a.getData() != null && offa < Integer.MAX_VALUE) {

**Comment by mueller-physics** [comment]
The code giving you this error is not part of fairSIM itself, it is a fork of the JTransforms library maintained here:
https://github.com/fairSIM/JTransforms

The release version of the plugin includes the JTransform fork, if you build it yourself just make sure 
* either the fork 
* or the originial JTransforms (https://github.com/wendykierp/JTransforms)

is available in the classpath.
