### ISSUE TITLE
Possibility to use in a macro

### ISSUE THREAD

**Issue by lguerard** [fairSIM/fairSIM#6]
Hi,

I read in other issues that you would implement the 3D SIM reconstruction at some point and I was wondering if you had any updates on that ?

In the meanwhile I was thinking of using the plugin right now in a macro to loop through all the slices and at least be able to get reconstruction for a stack. Would it be possible to enter some parameters and use fairSIM in a macro ?

Thanks for your help !

**Comment by mueller-physics** [comment]
Hi,

there are some first steps towards full 3D in the development branch, but I need time to finish them and debug the code... I am currently somewhat busy with other projects, I hope I can continue the work on 3D end of 2016 or start of 2017.

Concerning the macros, that should be possible when you have some experience with writing ImageJ macros and Java... In https://github.com/fairSIM/fairSIM/blob/master/org/fairsim/fiji/TestPlugin.java you can find a script that runs a complete reconstruction (incl. parameter estimation, etc.) from ImageJ's plugin / macro feature. That might serve as a good starting point to implement your own macros.

Best regards,

Marcel

**Comment by lguerard** [comment]
Hi,

Good to hear about the full 3D part, I'll keep an eye on this Github then ! :)

I don't really have that much experience with Java plugins and packages etc..  But thanks, I will try to see if I can at least figure it out !

Best,
Laurent.

**Comment by mueller-physics** [comment]
Hi,

there is now a timeline for the 3D, if everything goes to plan it will be implemented this summer. There is no advanced macro function yet, but I am adding a feature to reconstruct time-lapse stacks... Maybe this will already help you?

**Comment by lguerard** [comment]
Hi,

Thanks for letting me know. However, I am currently between jobs so I can
have a look at the code this summer once it's finished.

Anyhow, thanks a lot for answering me back.

Best,

-------------------
Laurent Guerard
